linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    
    - gofmt
    - goimports
    - stylecheck

    - errorlint
    - wrapcheck
    
    - bodyclose
    - noctx
    
    - gosec
    
    - misspell
    - revive
    - sqlclosecheck
    
    - exhaustive
    - exhaustruct
    - goconst
    - gocyclo
    
  presets:
    - bugs
    - error
    - format
    - performance
    - style

  fast: true

linters-settings:
  errcheck:
    check-type-assertions: true
  govet: {}
  revive:
    rules:
      - name: var-naming
        disabled: false
  gosec:
    includes:
      - G101
      - G102
      - G103
      - G104
      - G106
      - G107
      - G108
      - G109
      - G110
      - G111
      - G112
      - G113
      - G114
      - G201
      - G202
      - G203
      - G204
      - G301
      - G302
      - G303
      - G304
      - G305
      - G306
      - G307
      - G401
      - G402
      - G403
      - G404
      - G501
      - G502
      - G503
      - G504
      - G505
      - G601
      - G602
    excludes:
      - G101
    confidence: high
    config:
      global:
        audit: true
      G201: true
      G202: true
      G304: true
      G402: true
      G109: true

  stylecheck:
    checks: ["all"]
  gocyclo:
    min-complexity: 15 
  exhaustruct:
    include:
      - '.*\.Request$'
      - '.*\.Response$'
      - '.*\.Config$'

output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false